
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bntexxit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtexttt = new javax.swing.JTextArea();
        resetbtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tao = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        chuoi = new javax.swing.JRadioButton();
        cam = new javax.swing.JRadioButton();
        dua = new javax.swing.JRadioButton();
        duahau = new javax.swing.JRadioButton();
        xoai = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        coca = new javax.swing.JRadioButton();
        fanta = new javax.swing.JRadioButton();
        soda = new javax.swing.JRadioButton();
        pepsi = new javax.swing.JRadioButton();
        enegy = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        pho = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        pizza = new javax.swing.JRadioButton();
        milk = new javax.swing.JRadioButton();
        banhmi = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("FOOD MANAGEMENT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 390, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ORDER NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, 210, -1));

        bntexxit.setBackground(new java.awt.Color(51, 51, 0));
        bntexxit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bntexxit.setForeground(new java.awt.Color(255, 51, 51));
        bntexxit.setText("EXIT");
        bntexxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntexxitActionPerformed(evt);
            }
        });
        getContentPane().add(bntexxit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jtexttt.setBackground(new java.awt.Color(255, 255, 255));
        jtexttt.setColumns(20);
        jtexttt.setRows(5);
        jScrollPane1.setViewportView(jtexttt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 650, 130));

        resetbtn.setBackground(new java.awt.Color(255, 255, 255));
        resetbtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(51, 51, 51));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 730, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/387521026_864631395011711_739950961741095967_n.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/banana-juice.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("BANANAJUICE");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        tao.setBackground(new java.awt.Color(255, 255, 255));
        tao.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        tao.setForeground(new java.awt.Color(0, 0, 0));
        tao.setText("15.000 VND");
        getContentPane().add(tao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 91, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/orange-juice (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/coconut.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/watermelon-juice.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/mango.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/soda-bottle.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ORANGE JUICE");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("COCONUT JUICE");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("MANGO JUICE");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("MELON JUICE");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("FANTA");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        chuoi.setBackground(new java.awt.Color(255, 255, 255));
        chuoi.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        chuoi.setForeground(new java.awt.Color(0, 0, 0));
        chuoi.setText("20.000 VND");
        getContentPane().add(chuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 91, -1));

        cam.setBackground(new java.awt.Color(255, 255, 255));
        cam.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        cam.setForeground(new java.awt.Color(0, 0, 0));
        cam.setText("12.000 VND");
        cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camActionPerformed(evt);
            }
        });
        getContentPane().add(cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 91, -1));

        dua.setBackground(new java.awt.Color(255, 255, 255));
        dua.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        dua.setForeground(new java.awt.Color(0, 0, 0));
        dua.setText("12.000VND");
        getContentPane().add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 91, -1));

        duahau.setBackground(new java.awt.Color(255, 255, 255));
        duahau.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        duahau.setForeground(new java.awt.Color(0, 0, 0));
        duahau.setText("20.000 VND");
        getContentPane().add(duahau, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 91, -1));

        xoai.setBackground(new java.awt.Color(255, 255, 255));
        xoai.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        xoai.setForeground(new java.awt.Color(0, 0, 0));
        xoai.setText("17.000 VND");
        xoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaiActionPerformed(evt);
            }
        });
        getContentPane().add(xoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 91, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/vegetables.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("CHOICE JUICE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("FOOD");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/orange-juice (2).png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/soda.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/soda-bottle (1).png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/energy-drink.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/apple-juice.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        coca.setBackground(new java.awt.Color(255, 255, 255));
        coca.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        coca.setForeground(new java.awt.Color(0, 0, 0));
        coca.setText("13.000 VND");
        getContentPane().add(coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        fanta.setBackground(new java.awt.Color(255, 255, 255));
        fanta.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        fanta.setForeground(new java.awt.Color(0, 0, 0));
        fanta.setText("13.000 VND");
        getContentPane().add(fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        soda.setBackground(new java.awt.Color(255, 255, 255));
        soda.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        soda.setForeground(new java.awt.Color(0, 0, 0));
        soda.setText("10.000 VND");
        getContentPane().add(soda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 90, -1));

        pepsi.setBackground(new java.awt.Color(255, 255, 255));
        pepsi.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        pepsi.setForeground(new java.awt.Color(0, 0, 0));
        pepsi.setText("13.000 VND");
        getContentPane().add(pepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        enegy.setBackground(new java.awt.Color(255, 255, 255));
        enegy.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        enegy.setForeground(new java.awt.Color(0, 0, 0));
        enegy.setText("12.000 VND");
        getContentPane().add(enegy, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("CHOICE DRINK");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("APPLE JUICE");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/soft-drink.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 73, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("LEMON SODA");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("PEPSI");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("ENEGY DRINK");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("COCA COLA");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/banh-mi.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 60, 40));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("BANH MI");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/milk (1).png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("MILK");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/pho.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/pizza.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("PHO");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        pho.setBackground(new java.awt.Color(255, 255, 255));
        pho.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        pho.setForeground(new java.awt.Color(0, 0, 0));
        pho.setText("25.000 VND");
        getContentPane().add(pho, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("PIZZA");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        pizza.setBackground(new java.awt.Color(255, 255, 255));
        pizza.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        pizza.setForeground(new java.awt.Color(0, 0, 0));
        pizza.setText("60.000 VND");
        getContentPane().add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        milk.setBackground(new java.awt.Color(255, 255, 255));
        milk.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        milk.setForeground(new java.awt.Color(0, 0, 0));
        milk.setText("10.000 VND");
        getContentPane().add(milk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        banhmi.setBackground(new java.awt.Color(255, 255, 255));
        banhmi.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        banhmi.setForeground(new java.awt.Color(0, 0, 0));
        banhmi.setText("15.000 VND");
        getContentPane().add(banhmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/fast-food.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Screenshot 2023-10-11 102138.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 360, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Screenshot 2023-10-11 102138.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camActionPerformed


    }//GEN-LAST:event_camActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder sb = new StringBuilder();
        int n=0;
        if (cam.isSelected()) {  
            n+=12000;
            sb.append("You Chose Orange Juice!\n");
        } else {
            sb.append("");
        }
        if (tao.isSelected()) {
            n+=15000;
            sb.append("You Chose Apple Juice!\n");
        } else {
            sb.append("");
        }
        if (chuoi.isSelected()) {
            n+=20000;
            sb.append("You Chose Banana Juice!\n");
        } else {
            sb.append("");
        }
        if (dua.isSelected()) {
            n+=12000;
            sb.append("You Chose Coconut Juice!\n");
        } else {
            sb.append("");
        }
        if (duahau.isSelected()) {
            n+=20000;
            sb.append("You Chose Watermelon Juice!\n");
        } else {
            sb.append("");
        }
        if (xoai.isSelected()) {
            n+=17000;
            sb.append("You Chose Mango Juice!\n");
        } else {
            sb.append("");
        }
        if (coca.isSelected()) {
            n+=13000;
            sb.append("You Chose COCA COLA Drink!\n");
        } else {
            sb.append("");
        }
        if (fanta.isSelected()) {
            n+=13000;
            sb.append("You Chose Fanta Drink!\n");
        } else {
            sb.append("");
        }
        if (soda.isSelected()) {
            n+=10000;
            sb.append("You Chose Soda Drink!\n");
        } else {
            sb.append("");
        }
        if (pepsi.isSelected()) {
            n+=13000;
            sb.append("You Chose Pepsi Drink!\n");
        } else {
            sb.append("");
        }
        if (enegy.isSelected()) {
            n+=12000;
            sb.append("You Chose Enegy Drink!\n");

        } else {
            sb.append("");
        }
        if (milk.isSelected()) {
            n+=10000;
            sb.append("You Chose Milk!\n");

        } else {
            sb.append("");
        }if (pizza.isSelected()) {
            n+=60000;
            sb.append("You Chose Pizza!\n");

        } else {
            sb.append("");
        }if (banhmi.isSelected()) {
            n+=15000;
            sb.append("You Chose Banh Mi!\n");

        } else {
            sb.append("");
        }if (pho.isSelected()) {
            n+=25000;
            sb.append("You Chose Pho Noodle!\n");

        } else {
            sb.append("");
        }
        jtexttt.setText("-------------------------------\n" + sb.toString() + "-------------------------------\n" + "TOTAL Is: " + n + " VND\n" + "\nThank You <3");
        if (sb.toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Chose!", "Noti", HEIGHT);
            jtexttt.setText("Please Choce!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        JOptionPane.showMessageDialog(this, "RESET Complete", "Noti", JOptionPane.NO_OPTION);
        jtexttt.setText("");
        cam.setSelected(false);
        tao.setSelected(false);
        dua.setSelected(false);
        xoai.setSelected(false);
        duahau.setSelected(false);
        chuoi.setSelected(false);
        coca.setSelected(false);
        fanta.setSelected(false);
        soda.setSelected(false);
        enegy.setSelected(false);
        pepsi.setSelected(false);
        milk.setSelected(false);
        pizza.setSelected(false);
        banhmi.setSelected(false);
        pho.setSelected(false);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void bntexxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntexxitActionPerformed
        int e = JOptionPane.showConfirmDialog(this, "Are You Sure Exit ?");
        if (e == 0) {
            JOptionPane.showMessageDialog(this, "EXIT!", "Noti", JOptionPane.NO_OPTION);
            System.exit(0);
        }
        if (e == 1) {
            JOptionPane.showMessageDialog(this, "Continue Chose", "Noti", JOptionPane.NO_OPTION);
            return;
        }
        if (e == 2) {
            return;
        }
    }//GEN-LAST:event_bntexxitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chuoi.setSelected(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cam.setSelected(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dua.setSelected(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        duahau.setSelected(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        xoai.setSelected(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        coca.setSelected(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void xoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoaiActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        fanta.setSelected(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        soda.setSelected(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        pepsi.setSelected(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        enegy.setSelected(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        tao.setSelected(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        banhmi.setSelected(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        milk.setSelected(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        pho.setSelected(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        pizza.setSelected(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banhmi;
    private javax.swing.JButton bntexxit;
    private javax.swing.JRadioButton cam;
    private javax.swing.JRadioButton chuoi;
    private javax.swing.JRadioButton coca;
    private javax.swing.JRadioButton dua;
    private javax.swing.JRadioButton duahau;
    private javax.swing.JRadioButton enegy;
    private javax.swing.JRadioButton fanta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtexttt;
    private javax.swing.JRadioButton milk;
    private javax.swing.JRadioButton pepsi;
    private javax.swing.JRadioButton pho;
    private javax.swing.JRadioButton pizza;
    private javax.swing.JButton resetbtn;
    private javax.swing.JRadioButton soda;
    private javax.swing.JRadioButton tao;
    private javax.swing.JRadioButton xoai;
    // End of variables declaration//GEN-END:variables
}
